# Generated by Django 5.2.8 on 2025-11-15 16:45

import django.db.models.deletion
import flare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('AvatarID', models.AutoField(primary_key=True, serialize=False)),
                ('AvatarName', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('Taskname', models.CharField(max_length=100)),
                ('coinValue', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('passwordhash', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('userXP', models.PositiveIntegerField(default=0)),
                ('coinBalance', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('SessionID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100)),
                ('Study_Duration', models.DurationField()),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flare.user')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('entryID', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateField()),
                ('FriendID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='flare.user')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='flare.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('expiryDate', models.DateField(default=flare.models.one_day_from_now)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='flare.task')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='flare.user')),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('ChallengeID', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('isFull', models.BooleanField(default=False)),
                ('MaxSize', models.PositiveIntegerField()),
                ('ChallengeTitle', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=255)),
                ('CreatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('progress', models.PositiveIntegerField()),
                ('ChallengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.challenges')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.user')),
            ],
            options={
                'unique_together': {('UserID', 'ChallengeID')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('ChallengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.challenges')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.user')),
            ],
            options={
                'unique_together': {('userID', 'ChallengeID')},
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvatarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.avatar')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flare.user')),
            ],
            options={
                'unique_together': {('AvatarID', 'UserID')},
            },
        ),
    ]
